### ISSUE TITLE
No standard documentation for your library | Poor Documentation

### ISSUE THREAD

**Issue by reprogamaco** [Mehrabios/StyleWave#4]
I wonder it could be nice, if you could provide a nice well documentation like a github page, so we can see what the library does.
Thanks

**Comment by Mehrabios** [comment]
Hello!

Thanks for your interest in the library. Currently, I'm working on other projects and don't have the time to create comprehensive documentation. However, I plan to provide thorough documentation for the library in the near future, along with additional features and improvements.

I appreciate you opening this issue and sharing your thoughts.

Stay tuned for future updates!
Mehrab
